///
/// Project : Time tracking system
/// Created On : 10.5.2015
/// 
///
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

/// <summary>
/// const class to store all the sql queries at one place
/// </summary>
namespace TimeSheet.APP_CODE.DAL
{
    public class SQL_STRINGS
    {
        public static String SQL_GET_TIMESHEET_FOR_EMP = "SELECT ID,PROJECT_ID, PROJECT_NAME, TASK_JIRA_ISSUE_PROXY_KEY, HOURS_PER_DAY, COMMENTS FROM TIMESHEET WHERE EMPLOYEE_ID = @EMPLOYEE_ID ORDER BY ENTRY_ADD_DATE DESC";
        public static String SQL_GET_TIMESHEET_FOR_EMP_FOR_DATE = "SELECT ID,PROJECT_ID, PROJECT_NAME, TASK_JIRA_ISSUE_PROXY_KEY, HOURS_PER_DAY, COMMENTS FROM TIMESHEET WHERE EMPLOYEE_ID = @EMPLOYEE_ID AND TIMESHEET_DATE = CONVERT(DATETIME,@TDATE,101) ORDER BY ENTRY_ADD_DATE DESC";
        public static String SP_INSERT_TIMESHEET_ENTRY = "SP_INSERT_TIMESHEET_ENTRY";
        public static String SP_UPDATE_TIMESHEET_ENTRY = "SP_UPDATE_TIMESHEET_ENTRY";
        public static String SQL_DELETE_TIMESHEET_RECORD = "DELETE FROM TIMESHEET WHERE ID = @ROW_ID";
        public static String SQL_GET_EMPLOYEE = "SELECT (FIRST_NAME + ' ' + LAST_NAME) AS NAME, EMPLOYEE_ID FROM USER_LOGIN";
        public static String SP_ADD_NEW_USER = "SP_ADD_NEW_USER";
        public static String SQL_VALIDATE_LOGIN = "SELECT EMPLOYEE_ID, PASS, USER_GUID, IS_ADMIN, FIRST_NAME ,LAST_NAME,EMAIL_ID ,USER_GUID FROM USER_LOGIN WHERE EMPLOYEE_ID = @EMPLOYEE_ID";
        public static String SQL_GET_ALL_USERS = "SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL_ID,IS_ADMIN,USER_GUID FROM USER_LOGIN";
        public static String SP_UPDATE_ACCOUNT_INFO = "SP_UPDATE_ACCOUNT_INFO";
        public static String SP_RESET_PASS_USER = "SP_RESET_PASS_USER";
        public static String SQL_DELETE_USER_ACC = "DELETE FROM USER_LOGIN WHERE EMPLOYEE_ID = @EMP_ID";
        public static String SP_RESET_USER_PASS_ADMIN = "SP_RESET_USER_PASS_ADMIN";
        public static String SP_UPDATE_USER_TYPE_ADMIN = "SP_UPDATE_USER_TYPE_ADMIN";
        public static String SQL_GET_REPORT_DATA = "SELECT * FROM TIMESHEET ";
        public static String SQL_GET_REPORT_DATA_DATE_FILTER = " TIMESHEET_DATE BETWEEN @STARTDATE AND @ENDDATE";
        public static String SQL_GET_REPORT_DATA_PROJECT_FILTER = " PROJECT_ID IN ()";

    }
}