-- TABLE SCHEMA

DROP TABLE TIMESHEET;

CREATE TABLE TIMESHEET
(
ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
EMPLOYEE_ID VARCHAR(255) NOT NULL,
PROJECT_ID NUMERIC(18,0) NOT NULL,
PROJECT_NAME VARCHAR(255) NOT NULL,
TASK_JIRA_ISSUE_PROXY_KEY VARCHAR(255) NOT NULL,
TIMESHEET_DATE DATE NOT NULL,
HOURS_PER_DAY NUMERIC NOT NULL  CHECK(HOURS_PER_DAY > 0 AND HOURS_PER_DAY <=24),
COMMENTS VARCHAR(2000),
LAST_MODIFIED_DATE DATETIME
);

IF ( OBJECT_ID('SP_INSERT_TIMESHEET_ENTRY') IS NOT NULL ) 
   DROP PROCEDURE SP_INSERT_TIMESHEET_ENTRY
GO

CREATE PROCEDURE SP_INSERT_TIMESHEET_ENTRY
       @EMPLOYEE_ID VARCHAR(255),
       @PROJECT_ID NUMERIC(18,0),
       @PROJECT_NAME VARCHAR(255),
       @TASK_JIRA_ISSUE_PROXY_KEY VARCHAR(255),
       @TIMESHEET_DATE VARCHAR(10),
       @HOURS_PER_DAY NUMERIC,
       @COMMENTS VARCHAR(2000)
AS
BEGIN 
	DECLARE 
	@TOTAL_HOURS NUMERIC,
	@FOR_DATE DATE;
-- Check the total number of hours already submitted for the date
		
	SELECT @FOR_DATE = CONVERT(DATE,@TIMESHEET_DATE,101);
	SELECT @TOTAL_HOURS = SUM(HOURS_PER_DAY) FROM TIMESHEET WHERE EMPLOYEE_ID = @EMPLOYEE_ID AND TIMESHEET_DATE = @FOR_DATE;
    
    IF @TOTAL_HOURS = 24
	-- already 24 hours submitted
		RETURN -2 ;
	ELSE
	BEGIN 
		-- sum of submitted plus this entry is > 24
		IF (@TOTAL_HOURS+@HOURS_PER_DAY) > 24
		RETURN -1;
		ELSE
		BEGIN
			INSERT INTO TIMESHEET VALUES(@EMPLOYEE_ID, @PROJECT_ID, @PROJECT_NAME, @TASK_JIRA_ISSUE_PROXY_KEY,@FOR_DATE,@HOURS_PER_DAY,@COMMENTS,CURRENT_TIMESTAMP);
			IF @@ROWCOUNT = 1
				RETURN 1;
			ELSE
				RETURN 0;
		END
	END
END 



	
